version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql-db:3306/windpro
    volumes:
      - /Users/krystianpietrzak/Documents/ML/WindPRO/mlruns:/app/mlruns

  mysql-db:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wind_pro
      MYSQL_ROOT_PASSWORD: password
